image: ubuntu:latest
variables:
  TF_ROOT: ${CI_PROJECT_DIR}

cache:
  key: terraform-cache
  paths:
    - ${TF_ROOT}/.terraform
    - ${TF_ROOT}/.terraform.lock.hcl
    - ${TF_ROOT}/terraform.tfstate
    - ${TF_ROOT}/terraform.tfstate.backup
    - ${TF_ROOT}/.ssh
    - ${TF_ROOT}/ansible/inventory
  when: always

before_script:
  - apt-get update -y
  - apt-get install -y wget gpg gnupg software-properties-common
  - wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
  - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
  - apt-get update -y
  - apt-get install -y terraform
  - apt-get install -y python3-pip
  - pip3 install --upgrade pip
  - python3 -m pip install --user ansible 
  - cd ${TF_ROOT}

stages:
  - build_image
  - prepare
  - validate
  - build
  - deploy
  - destroy

init:
  stage: prepare
  script:
    - terraform init

validate:
  stage: validate
  script:
    - terraform init
    - terraform validate

plan:
  stage: build
  script:
    - terraform plan
    - terraform plan-json
  artifacts:
    name: plan
    paths:
      - ${TF_ROOT}/plan.cache
    reports:
      terraform: ${TF_ROOT}/plan.json

apply:
  stage: deploy
  environment:
    name: production
  script:
    - terraform apply
  dependencies:
    - plan
  when: manual

destroy:
  stage: destroy
  environment:
    name: production
  script:
    - terraform destroy
  when: manual
