build_image:
  stage: build_image
  image: docker
  services:
    - docker:dind
  script: 
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  only:
    changes:
      - Dockerfile

image: $CI_REGISTRY_IMAGE
variables:
  TF_ROOT: ${CI_PROJECT_DIR}

cache:
  key: terraform-cache
  paths:
    - ${TF_ROOT}/.terraform
    - ${TF_ROOT}/.terraform.lock.hcl
    - ${TF_ROOT}/terraform.tfstate
    - ${TF_ROOT}/terraform.tfstate.backup
    - ${TF_ROOT}/.ssh
    - ${TF_ROOT}/ansible/inventory
  when: always

before_script:
  - cd ${TF_ROOT}

stages:
  - build_image
  - prepare
  - validate
  - build
  - deploy
  - destroy

init:
  stage: prepare
  script:
    - terraform init

validate:
  stage: validate
  script:
    - terraform init
    - terraform validate

plan:
  stage: build
  script:
    - terraform plan
    - terraform plan-json
  artifacts:
    name: plan
    paths:
      - ${TF_ROOT}/plan.cache
    reports:
      terraform: ${TF_ROOT}/plan.json

apply:
  stage: deploy
  environment:
    name: production
  script:
    - terraform apply
  dependencies:
    - plan
  when: manual

destroy:
  stage: destroy
  environment:
    name: production
  script:
    - terraform destroy
  when: manual
