image: registry.code.fbi.h-da.de/cloud-computing-technology/2022_wise/group_a_2:latest
variables:
  TF_ROOT: ${CI_PROJECT_DIR}

cache:
  key: terraform-cache
  paths:
    - ${TF_ROOT}/.terraform
    - ${TF_ROOT}/.terraform.lock.hcl
    - ${TF_ROOT}/terraform.tfstate
    - ${TF_ROOT}/terraform.tfstate.backup
    - ${TF_ROOT}/plan
    - ${TF_ROOT}/plan.json
    - ${TF_ROOT}/.ssh
    - ${TF_ROOT}/ansible/inventory
  when: always

before_script:
  - cd ${TF_ROOT}

stages:
  - init
  - validate
  - plan
  - apply
  - destroy

init:
  stage: init
  script:
    - terraform init
  artifacts:
    name: init
    paths:
    - ${TF_ROOT}/.terraform
    - ${TF_ROOT}/.terraform.lock.hcl

validate:
  stage: validate
  script:
    - terraform validate
  dependencies:
    - init

plan:
  stage: plan
  script:
    - terraform plan -out=${TF_ROOT}/plan
    - terraform show -json ${TF_ROOT}/plan | jq > ${TF_ROOT}/plan.json
  artifacts:
    name: plan
    paths:
      - ${TF_ROOT}/plan
    reports:
      terraform: ${TF_ROOT}/plan.json
  dependencies:
    - init
    - validate

apply:
  stage: apply
  environment:
    name: production
  script:
    - terraform apply ${TF_ROOT}/plan
  artifacts:
    name: apply
    paths:
    - ${TF_ROOT}/terraform.tfstate
    - ${TF_ROOT}/terraform.tfstate.backup
    - ${TF_ROOT}/.ssh
    - ${TF_ROOT}/ansible/inventory
  dependencies:
    - init
    - validate
    - plan
  when: manual

destroy:
  stage: destroy
  environment:
    name: production
  script:
    - terraform destroy -auto-approve
  dependencies:
    - init
    - validate
    - plan
    - apply
  when: manual
