# https://www.bitslovers.com/run-terraform-from-gitlab-ci/
# https://medium.com/geekculture/how-to-run-terraform-script-using-gitlab-ci-cd-b6f448ab0232

stages:
  - validate
  - plan
  - apply
  - destroy


validate:
  stage: validate
  before_script:
    - rm -rf .terraform
    - gitlab-terraform --version
    - gitlab-terraform init
  script:
    - gitlab-terraform validate

plan:
  stage: plan
  script:
    - gitlab-terraform plan -out "planfile"
  dependencies:
    - validate
  artifacts:
    paths:
      - planfile

apply:
  stage: apply
  script:
    - gitlab-terraform apply -input=false "planfile"
  dependencies:
    - plan
  when: manual

destroy:
  stage: destroy
  script:
    - gitlab-terraform destroy --auto-approve 
  when: manual