- hosts: masters[0] # run only on the first master node
  name: Configure masters
  become: true

  tasks:
    - name: Initialize the cluster
      ansible.builtin.shell: |
        kubeadm init \
        --control-plane-endpoint={{ load_balancer_kubernetes_masters }}:6443 \
        --pod-network-cidr=10.44.0.0/16 \
        --apiserver-cert-extra-sans={{ load_balancer_kubernetes_masters }}
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: Configure kubectl
      become: true
      become_user: kube
      ansible.builtin.shell: |
        mkdir -p $HOME/.kube
        sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        sudo chown $(id -u):$(id -g) $HOME/.kube/config
        
    - name: Deploy a pod network
      become: true
      become_user: kube
      ansible.builtin.shell: |
              kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml

    - name: Get the token for joining the nodes
      ansible.builtin.shell: kubeadm token create --print-join-command
      register: kubernetes_join_command

    - name: Copy join command to local file
      become: false
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command"

    - name: Get the certificate key for joining the master nodes
      ansible.builtin.shell: kubeadm init phase upload-certs --upload-certs
      register: kubernetes_certificate_key

    - name: Copy certificate key to local file
      become: false
      local_action: copy content="{{ kubernetes_certificate_key.stdout_lines[0] }} --control-plane --certificate-key {{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_masters_join_command"
