- hosts: "masters, workers"
  name: Install kubernetes
  become: true
  become_method: sudo
  become_user: root
  gather_facts: true
  connection: ssh

  tasks:
     - name: Create containerd config file
       ansible.builtin.file:
          path: "/etc/modules-load.d/containerd.conf"
          state: "touch"

     - name: Add conf for containerd
       ansible.builtin.blockinfile:
          path: "/etc/modules-load.d/containerd.conf"
          block: |
               overlay
               br_netfilter

     - name: Modprobe
       ansible.builtin.shell: |
               sudo modprobe overlay
               sudo modprobe br_netfilter

     - name: Set system configurations for kubernetes networking
       ansible.builtin.file:
          path: "/etc/sysctl.d/99-kubernetes-cri.conf"
          state: "touch"

     - name: Add conf for containerd
       ansible.builtin.blockinfile:
          path: "/etc/sysctl.d/99-kubernetes-cri.conf"
          block: |
                net.bridge.bridge-nf-call-iptables = 1
                net.ipv4.ip_forward = 1
                net.bridge.bridge-nf-call-ip6tables = 1

     - name: Apply new settings
       ansible.builtin.command: sudo sysctl --system

     - name: Install containerd, runc and cni
       ansible.builtin.shell: |
               curl -L -O https://github.com/containerd/containerd/releases/download/v1.6.12/containerd-1.6.12-linux-amd64.tar.gz
               sudo tar Cxzvf /usr/local containerd-1.6.12-linux-amd64.tar.gz
               curl -O https://raw.githubusercontent.com/containerd/containerd/main/containerd.service
               sudo mkdir -p /usr/local/lib/systemd/system
               sudo cp containerd.service /usr/local/lib/systemd/system/containerd.service
               curl -L -O https://github.com/opencontainers/runc/releases/download/v1.1.4/runc.amd64
               sudo install -m 755 runc.amd64 /usr/local/sbin/runc
               curl -L -O https://github.com/containernetworking/plugins/releases/download/v1.1.1/cni-plugins-linux-amd64-v1.1.1.tgz
               sudo mkdir -p /opt/cni/bin
               sudo tar Cxzvf /opt/cni/bin cni-plugins-linux-amd64-v1.1.1.tgz
               sudo mkdir -p /etc/containerd
               sudo containerd config default | sudo tee /etc/containerd/config.toml
               sudo sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml
               sudo systemctl daemon-reload
               sudo systemctl enable --now containerd

     - name: Disable swap
       ansible.builtin.shell: |
               sudo swapoff -a 
               sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

     - name: Install and configure dependencies
       ansible.builtin.shell: |
               sudo apt-get update && sudo apt-get install -y apt-transport-https curl
               curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -

     - name: Create kubernetes repo file
       ansible.builtin.file:
          path: "/etc/apt/sources.list.d/kubernetes.list"
          state: "touch"

     - name: Add kubernetes source
       ansible.builtin.blockinfile:
          path: "/etc/apt/sources.list.d/kubernetes.list"
          block: |
               deb https://apt.kubernetes.io/ kubernetes-xenial main

     - name: Install kubelet, kubeadm and kubectl
       ansible.builtin.shell: |
               sudo apt-get update
               sudo apt-get install -y kubelet kubeadm kubectl
               sudo apt-mark hold kubelet kubeadm kubectl

     - name: Enable kubelet
       ansible.builtin.shell: |
               sudo systemctl enable --now kubelet
