- hosts: workers
  name: Let the workers join the cluster

  tasks:
   - name: Wait until the file /tmp/kubernetes_join_command is present
     delegate_to: localhost
     ansible.builtin.wait_for:
      path: /tmp/kubernetes_join_command

   - name: Copy join command from Ansiblehost to the worker nodes
     become: true
     ansible.builtin.copy:
      src: /tmp/kubernetes_join_command
      dest: /tmp/kubernetes_join_command
      mode: 0777

   - name: Join the worker nodes to the cluster
     become: true
     ansible.builtin.command: sh /tmp/kubernetes_join_command
     register: joined_or_not
