- hosts: workers
  name: Let the workers join the cluster

  tasks:
   - name: Copy join command from Ansiblehost to the worker nodes
     become: true
     become_user: kube
     ansible.builtin.copy:
      src: /tmp/kubernetes_join_command
      dest: /tmp/kubernetes_join_command
      mode: 0777

   - name: Join the worker nodes to the cluster
     become: true
     become_user: kube
     ansible.builtin.command: sh /tmp/kubernetes_join_command
     register: joined_or_not
