- hosts: masters[1:] # all masters except the first
  name: Let the masters join the cluster

  tasks:
   - name: Wait until the file /tmp/kubernetes_masters_join_command is present
     ansible.builtin.wait_for:
      path: /tmp/kubernetes_masters_join_command

   - name: Copy join command from Ansiblehost to the master nodes
     become: true
     become_user: kube
     ansible.builtin.copy:
      src: /tmp/kubernetes_masters_join_command
      dest: /tmp/kubernetes_masters_join_command
      mode: 0777

   - name: Join the master nodes to the cluster
     become: true
     become_user: kube
     ansible.builtin.command: sh /tmp/kubernetes_masters_join_command
     register: joined_or_not
