- hosts: masters[0]

  tasks:
    - name: Install prometheus
      become: true
      become_user: kube
      ansible.builtin.shell: |
              helm repo add my-repo https://charts.bitnami.com/bitnami
              helm repo update
              helm install my-release my-repo/apache --set replicaCount=5
#              kubectl patch service stable-grafana --patch='{"spec": {"type": "NodePort"}}'
#               kubectl patch service stable-grafana --type='json' --patch='[{"op": "replace", "path": "/spec/ports/0/nodePort", "value":31000}]'
