- hosts: masters
  tasks:
    - name: install prometheus
      become: yes
      become_user: kube
      shell: |
              helm repo add apache-repo https://charts.bitnami.com/bitnami
              helm repo update
              helm install apache-release apache-repo/apache--set replicaCount=5
#              kubectl patch service stable-grafana --patch='{"spec": {"type": "NodePort"}}'
#               kubectl patch service stable-grafana --type='json' --patch='[{"op": "replace", "path": "/spec/ports/0/nodePort", "value":31000}]'
