- hosts: masters[0]

  tasks:
    - name: Install ingress controller
      become: true
      become_user: kube
      ansible.builtin.shell: |
              helm upgrade --install ingress-nginx ingress-nginx --repo https://kubernetes.github.io/ingress-nginx --namespace ingress-nginx --create-namespace
