- hosts: masters
  tasks:
    - name: install ingress controller
      become: yes
      become_user: kube
      shell: |
              helm upgrade --install ingress-nginx ingress-nginx --repo https://kubernetes.github.io/ingress-nginx --namespace ingress-nginx --create-namespace
