- name: Install helm
  ansible.builtin.import_playbook: install-helm.yml

- name: Install ingress controller
  ansible.builtin.import_playbook: ingress-controller.yml

- name: Install prometheus
  ansible.builtin.import_playbook: prometheus.yml

- name: Install apache2
  ansible.builtin.import_playbook: apache2.yml
