- name: install helm
  ansible.builtin.import_playbook: install-helm.yml

- name: install ingress controller
  ansible.builtin.import_playbook: ingress-controller.yml
  
- name: install prometheus
  ansible.builtin.import_playbook: prometheus.yml
