- hosts: masters[0]

  tasks:
    - name: Install prometheus
      become: true
      become_user: kube
      ansible.builtin.shell: |
              helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
              helm repo update
              helm install stable prometheus-community/kube-prometheus-stack --set grafana.adminPassword="tfcct2022"
              kubectl patch service stable-grafana --patch='{"spec": {"type": "NodePort"}}'
              kubectl patch service stable-grafana --type='json' --patch='[{"op": "replace", "path": "/spec/ports/0/nodePort", "value":{{ grafana_port }}}]'
